<?php

namespace Tests\Feature;

use App\Enums\JobStatus;
use App\Jobs\UploadFileJob;
use App\Models\FileJob;
use App\Models\StorageAccount;
use App\Models\StorageProvider;
use App\Models\User;
use App\Models\VirtualFile;
use App\Services\Storage\StorageManager;
use App\Services\Storage\ThumbnailService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\FakeDriver;
use Tests\TestCase;

class ThumbnailTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    private StorageAccount $account;

    private ThumbnailService $thumbnailService;

    protected function setUp(): void
    {
        parent::setUp();

        FakeDriver::reset();

        $this->user = User::create([
            'name' => 'Owner',
            'email' => 'owner@test.local',
            'password' => bcrypt('secret'),
        ]);

        $provider = StorageProvider::create([
            'name' => 'fake',
            'driver_class' => FakeDriver::class,
            'is_active' => true,
        ]);

        $this->account = StorageAccount::create([
            'user_id' => $this->user->id,
            'storage_provider_id' => $provider->id,
            'alias' => 'Fake Storage',
            'quota_total' => 10 * 1024 ** 3,
            'quota_used' => 0,
            'status' => 'active',
        ]);

        $this->thumbnailService = app(ThumbnailService::class);

        $this->actingAs($this->user);
    }

    private function createSamplePngImage(): string
    {
        $im = imagecreatetruecolor(600, 400);
        $red = imagecolorallocate($im, 255, 0, 0);
        imagefilledrectangle($im, 0, 0, 600, 400, $red);

        $tempPath = app(StorageManager::class)->tempPath(uniqid('img_', true).'.png');
        app(StorageManager::class)->ensureTempDir();
        imagepng($im, $tempPath);
        imagedestroy($im);

        return $tempPath;
    }

    private function uploadImageFile(string $name = 'sample.png', string $mime = 'image/png'): VirtualFile
    {
        $tempPath = $this->createSamplePngImage();

        $row = FileJob::create([
            'user_id' => $this->user->id,
            'type' => 'upload',
            'virtual_folder_id' => null,
            'original_name' => $name,
            'size' => filesize($tempPath),
            'mime_type' => $mime,
            'status' => JobStatus::Pending,
        ]);

        (new UploadFileJob($row->id, $tempPath, $this->account->id))
            ->handle(app(StorageManager::class), $this->thumbnailService);

        return VirtualFile::where('name', $name)->firstOrFail();
    }

    public function test_guest_cannot_access_thumbnail(): void
    {
        auth()->logout();

        $file = VirtualFile::create([
            'user_id' => $this->user->id,
            'storage_account_id' => $this->account->id,
            'name' => 'photo.jpg',
            'remote_ref' => 'ref-1',
            'size' => 1024,
            'mime_type' => 'image/jpeg',
            'is_chunked' => false,
        ]);

        $this->get("/files/{$file->id}/thumbnail")->assertRedirect(route('login'));
    }

    public function test_user_cannot_access_another_users_thumbnail(): void
    {
        $otherUser = User::create([
            'name' => 'Other',
            'email' => 'other@test.local',
            'password' => bcrypt('secret'),
        ]);

        $file = VirtualFile::create([
            'user_id' => $otherUser->id,
            'storage_account_id' => $this->account->id,
            'name' => 'secret.jpg',
            'remote_ref' => 'ref-2',
            'size' => 1024,
            'mime_type' => 'image/jpeg',
            'is_chunked' => false,
        ]);

        $this->get("/files/{$file->id}/thumbnail")->assertNotFound();
    }

    public function test_unsupported_file_type_returns_not_found(): void
    {
        $file = VirtualFile::create([
            'user_id' => $this->user->id,
            'storage_account_id' => $this->account->id,
            'name' => 'archive.zip',
            'remote_ref' => 'ref-zip',
            'size' => 2048,
            'mime_type' => 'application/zip',
            'is_chunked' => false,
        ]);

        $this->get("/files/{$file->id}/thumbnail")->assertNotFound();
    }

    public function test_upload_job_generates_thumbnail_and_serves_it(): void
    {
        $file = $this->uploadImageFile('banner.png', 'image/png');

        // Thumbnail should be pre-generated by UploadFileJob
        $this->assertTrue($this->thumbnailService->hasThumbnail($file));

        $response = $this->get("/files/{$file->id}/thumbnail");
        $response->assertOk();
        $response->assertHeader('Content-Type', 'image/webp');
        $this->assertStringContainsString('private', (string) $response->headers->get('Cache-Control'));
        $this->assertStringContainsString('max-age=604800', (string) $response->headers->get('Cache-Control'));
        $this->assertNotEmpty($response->headers->get('ETag'));

        // If-None-Match returns 304
        $etag = $response->headers->get('ETag');
        $cachedResponse = $this->withHeaders(['If-None-Match' => $etag])
            ->get("/files/{$file->id}/thumbnail");
        $cachedResponse->assertStatus(304);

        // Cleanup
        $this->thumbnailService->deleteThumbnail($file);
    }

    public function test_deleting_file_removes_its_cached_thumbnail(): void
    {
        $file = $this->uploadImageFile('to_delete.png', 'image/png');
        $this->assertTrue($this->thumbnailService->hasThumbnail($file));

        $this->delete("/files/{$file->id}")->assertRedirect();

        $this->assertFalse($this->thumbnailService->hasThumbnail($file));
    }

    public function test_thumbnail_service_supports_image_types(): void
    {
        $imageFile = new VirtualFile(['name' => 'photo.JPG', 'mime_type' => 'image/jpeg']);
        $webpFile = new VirtualFile(['name' => 'graphic.webp', 'mime_type' => 'image/webp']);
        $svgFile = new VirtualFile(['name' => 'vector.svg', 'mime_type' => 'image/svg+xml']);
        $docFile = new VirtualFile(['name' => 'document.pdf', 'mime_type' => 'application/pdf']);
        $codeFile = new VirtualFile(['name' => 'script.js', 'mime_type' => 'text/javascript']);

        $this->assertTrue($this->thumbnailService->supports($imageFile));
        $this->assertTrue($this->thumbnailService->supports($webpFile));
        $this->assertTrue($this->thumbnailService->supports($svgFile));
        $this->assertFalse($this->thumbnailService->supports($docFile));
        $this->assertFalse($this->thumbnailService->supports($codeFile));
    }

    public function test_svg_thumbnail_handling(): void
    {
        $file = VirtualFile::create([
            'user_id' => $this->user->id,
            'storage_account_id' => $this->account->id,
            'name' => 'logo.svg',
            'remote_ref' => 'ref-svg',
            'size' => 100,
            'mime_type' => 'image/svg+xml',
            'is_chunked' => false,
        ]);

        $svgContent = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="teal" /></svg>';
        $tempPath = app(StorageManager::class)->tempPath('logo.svg');
        file_put_contents($tempPath, $svgContent);

        $dest = $this->thumbnailService->generateThumbnail($file, $tempPath);
        @unlink($tempPath);

        $this->assertNotNull($dest);
        $this->assertFileExists($dest);
        $this->assertTrue($this->thumbnailService->hasThumbnail($file));

        $response = $this->get("/files/{$file->id}/thumbnail");
        $response->assertOk();
        $response->assertHeader('Content-Type', 'image/svg+xml');

        // Cleanup
        $this->thumbnailService->deleteThumbnail($file);
    }

    public function test_on_demand_thumbnail_generation_when_not_pre_cached(): void
    {
        $pngPath = $this->createSamplePngImage();
        $remoteRef = 'remote-img-1';
        FakeDriver::$storage[$remoteRef] = (string) file_get_contents($pngPath);
        @unlink($pngPath);

        $file = VirtualFile::create([
            'user_id' => $this->user->id,
            'storage_account_id' => $this->account->id,
            'name' => 'scanned_image.png',
            'remote_ref' => $remoteRef,
            'size' => strlen(FakeDriver::$storage[$remoteRef]),
            'mime_type' => 'image/png',
            'is_chunked' => false,
        ]);

        // Prior to GET request, thumbnail is not cached
        $this->assertFalse($this->thumbnailService->hasThumbnail($file));

        $response = $this->get("/files/{$file->id}/thumbnail");
        $response->assertOk();
        $response->assertHeader('Content-Type', 'image/webp');

        // Now it should be cached on disk
        $this->assertTrue($this->thumbnailService->hasThumbnail($file));

        // Cleanup
        $this->thumbnailService->deleteThumbnail($file);
    }
}
